// Code generated by vango. DO NOT EDIT.

package routes

import (
	"cli-test-app/app/routes/api"
	"github.com/vango-go/vango"
)

// Register adds all routes to the app.
// Generated by `vango dev` or `vango gen routes`.
func Register(app *vango.App) {
	// Layouts
	app.Layout("/layout", LayoutPage)

	// Pages
	app.Page("/about", AboutPage)
	app.Page("/", IndexPage)

	// API routes
	app.API("GET", "/api/health", api.HealthGET)
}

// Route path constants for type-safe linking.
const (
	RouteIndex = "/"
	RouteAbout = "/about"
)
